"use client";
import { useMemo, useState } from "react";
import { AlertCircle, ArrowLeft, CalendarDays, CheckCircle2, ChevronRight, Clock3, Download, Eye, FileCheck2, FileText, HelpCircle, MapPin, PackageCheck, Phone, Recycle, Search, Settings, ShieldCheck, Truck, Upload, UserRound } from "lucide-react";

export type WasteItem={id:string;type:string;quantity:number;unit:string;date:string;status:"Disponible"|"Retiro solicitado"|"Retirado";code:string};
type Props={waste:WasteItem[];query:string;setQuery:(q:string)=>void;onDeclare:()=>void;onPickup:()=>void;notify:(m:string)=>void};

const demoPickups=[
 {code:"SOL-2026-0341",date:"04 sep 2026",window:"09:00 – 12:00",status:"Confirmado",address:"Av. Irarrázaval 2450",items:"Aceite vegetal · Cartón",weight:"168 kg/L"},
 {code:"SOL-2026-0318",date:"26 ago 2026",window:"10:30 – 11:45",status:"Completado",address:"Av. Irarrázaval 2450",items:"Vidrio · Plásticos PET",weight:"111 kg"},
 {code:"SOL-2026-0287",date:"08 ago 2026",window:"15:00 – 16:20",status:"Completado",address:"Av. Irarrázaval 2450",items:"Cartón y papel",weight:"94 kg"}
];

function PageHead({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <section className="module-head"><div><p className="eyebrow"><span/>{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</section>}

export function WasteView({waste,query,setQuery,onDeclare,onPickup}:Props){const [filter,setFilter]=useState("Todos");const rows=useMemo(()=>waste.filter(w=>(filter==="Todos"||w.status===filter)&&`${w.type} ${w.code}`.toLowerCase().includes(query.toLowerCase())),[waste,filter,query]);return <>
 <PageHead eyebrow="Inventario trazable" title="Mis residuos" description="Administra todo el material declarado por tu empresa." action={<button className="primary" onClick={onDeclare}><Recycle/> Declarar residuo</button>}/>
 <section className="module-stats"><article><span>Total registrado</span><strong>{waste.reduce((a,w)=>a+w.quantity,0).toLocaleString("es-CL")} <small>kg/L</small></strong></article><article><span>Disponible</span><strong>{waste.filter(w=>w.status==="Disponible").length}</strong></article><article><span>En proceso</span><strong>{waste.filter(w=>w.status==="Retiro solicitado").length}</strong></article><article><span>Valorizado</span><strong>{waste.filter(w=>w.status==="Retirado").length}</strong></article></section>
 <section className="panel module-panel"><div className="toolbar"><div className="search wide"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar residuo o código de trazabilidad"/></div><div className="segmented">{["Todos","Disponible","Retiro solicitado","Retirado"].map(x=><button className={filter===x?"selected":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="table-wrap"><table><thead><tr><th>RESIDUO</th><th>CÓDIGO</th><th>CANTIDAD</th><th>DECLARACIÓN</th><th>ESTADO</th><th/></tr></thead><tbody>{rows.map((w,i)=><tr key={w.id}><td><div className={`waste-icon w${i%4}`}><Recycle/></div><strong>{w.type}</strong></td><td>{w.code}</td><td><strong>{w.quantity} {w.unit}</strong></td><td>{w.date}</td><td><span className={`status ${w.status.replace(" ","-").toLowerCase()}`}>{w.status}</span></td><td><button className="row-action"><Eye/> Ver</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No encontramos residuos con ese filtro."/>}</div><div className="table-foot"><span>{rows.length} registros</span>{waste.some(w=>w.status==="Disponible")&&<button onClick={onPickup}>Solicitar retiro de disponibles <ChevronRight/></button>}</div></section></>}

export function PickupView({onPickup,notify}:Props){const [selected,setSelected]=useState(demoPickups[0]);return <><PageHead eyebrow="Logística autorizada" title="Solicitudes de retiro" description="Coordina y sigue cada recolección en tiempo real." action={<button className="primary" onClick={onPickup}><Truck/> Nueva solicitud</button>}/><div className="split-view"><section className="panel request-list"><div className="list-tabs"><button className="active">Todas <b>3</b></button><button>Pendientes <b>1</b></button><button>Completadas <b>2</b></button></div>{demoPickups.map(p=><button key={p.code} className={`request-card ${selected.code===p.code?"selected":""}`} onClick={()=>setSelected(p)}><div><strong>{p.code}</strong><span className={`request-status ${p.status.toLowerCase()}`}>{p.status}</span></div><h3><CalendarDays/> {p.date} · {p.window}</h3><p><MapPin/> {p.address}</p><p><PackageCheck/> {p.items}</p><b>{p.weight}</b></button>)}</section><section className="panel request-detail"><div className="detail-title"><div><span>DETALLE DE SOLICITUD</span><h2>{selected.code}</h2></div><button onClick={()=>notify("Comprobante preparado para descarga")}><Download/> Comprobante</button></div><div className="tracking"><Track done icon={<FileText/>} title="Solicitud ingresada" meta="02 sep · 10:24"/><Track done icon={<CheckCircle2/>} title="Retiro confirmado" meta="02 sep · 12:08"/><Track active={selected.status==="Confirmado"} done={selected.status==="Completado"} icon={<Truck/>} title="Recolección" meta={selected.status==="Completado"?selected.date:"Programada para el 04 sep"}/><Track done={selected.status==="Completado"} icon={<Recycle/>} title="Recepción y valorización" meta={selected.status==="Completado"?"Planta certificada":"Pendiente"}/></div><div className="detail-grid"><div><span>Dirección</span><strong>{selected.address}</strong></div><div><span>Horario</span><strong>{selected.window}</strong></div><div><span>Contacto</span><strong>Carolina Muñoz</strong></div><div><span>Gestor asignado</span><strong>EcoRuta Gestión SpA</strong></div></div><div className="detail-notice"><ShieldCheck/> Este retiro será realizado por un gestor autorizado y quedará respaldado con un certificado digital.</div></section></div></>}

function Track({icon,title,meta,done=false,active=false}:{icon:React.ReactNode;title:string;meta:string;done?:boolean;active?:boolean}){return <div className={`track ${done?"done":""} ${active?"active":""}`}><i>{done?<CheckCircle2/>:icon}</i><div><strong>{title}</strong><span>{meta}</span></div></div>}

export function CertificatesView({notify}:Props){return <><PageHead eyebrow="Respaldo ambiental" title="Certificados" description="Descarga y verifica los comprobantes de valorización de tu empresa."/><section className="certificate-summary"><div><FileCheck2/><span><strong>3 certificados emitidos</strong><small>284 kg de residuos valorizados</small></span></div><div><ShieldCheck/><span><strong>100% verificables</strong><small>Firma y código de validación digital</small></span></div></section><section className="panel module-panel"><div className="panel-head"><div><h2>Documentos emitidos</h2><p>Certificados oficiales asociados a retiros completados</p></div></div><div className="certificate-list">{[["CER-2026-00291","26 ago 2026","Vidrio y plásticos PET","111 kg"],["CER-2026-00254","08 ago 2026","Cartón y papel","94 kg"],["CER-2026-00210","21 jul 2026","Aceite vegetal usado","79 L"]].map((c,i)=><article key={c[0]}><div className="pdf-icon"><FileText/></div><div><strong>{c[0]}</strong><span>{c[2]} · {c[1]}</span></div><b>{c[3]}</b><span className="verified"><CheckCircle2/> Verificado</span><button onClick={()=>notify(`Descargando ${c[0]}.pdf`)}><Eye/> Ver</button><button onClick={()=>notify(`Certificado ${c[0]} descargado`)}><Download/> PDF</button></article>)}</div></section></>}

export function HistoryView({waste}:Props){const events=[...waste.map(w=>({date:w.date,title:`Residuo declarado: ${w.type}`,code:w.code,kind:"declaration"})),{date:"26 ago 2026",title:"Retiro completado y certificado",code:"SOL-2026-0318",kind:"pickup"},{date:"26 ago 2026",title:"Certificado de valorización emitido",code:"CER-2026-00291",kind:"certificate"}];return <><PageHead eyebrow="Auditoría completa" title="Historial de actividad" description="Consulta todos los movimientos y responsables de la trazabilidad."/><section className="panel module-panel"><div className="toolbar"><div className="search wide"><Search/><input placeholder="Buscar por acción, código o residuo"/></div><button className="date-filter"><CalendarDays/> 01 ago – 02 sep</button></div><div className="timeline-list">{events.map((e,i)=><article key={`${e.code}-${i}`}><div className={`event-icon ${e.kind}`}>{e.kind==="pickup"?<Truck/>:e.kind==="certificate"?<FileCheck2/>:<Recycle/>}</div><div><strong>{e.title}</strong><span>{e.code} · Carolina Muñoz</span></div><time>{e.date}</time><button><ChevronRight/></button></article>)}</div></section></>}

export function HelpView({notify}:Props){return <><PageHead eyebrow="Estamos para ayudarte" title="Centro de ayuda" description="Resuelve dudas sobre declaraciones, retiros y normativa."/><section className="help-grid"><article className="panel"><Recycle/><h3>Declarar residuos</h3><p>Aprende qué información registrar y cómo acreditar el origen.</p><button onClick={()=>notify("Abriendo guía de declaraciones")}>Ver guía <ChevronRight/></button></article><article className="panel"><Truck/><h3>Solicitar un retiro</h3><p>Requisitos, horarios y preparación de materiales.</p><button onClick={()=>notify("Abriendo guía de retiros")}>Ver guía <ChevronRight/></button></article><article className="panel"><FileCheck2/><h3>Certificados</h3><p>Cómo descargar y validar documentos de valorización.</p><button onClick={()=>notify("Abriendo guía de certificados")}>Ver guía <ChevronRight/></button></article></section><section className="panel contact-support"><div><Phone/><span><strong>¿Necesitas ayuda personalizada?</strong><small>Lunes a viernes, 08:30 a 17:30 hrs</small></span></div><button onClick={()=>notify("Solicitud de soporte enviada")}>Contactar soporte</button></section></>}

export function SettingsView({notify}:Props){const [email,setEmail]=useState(true),[pickup,setPickup]=useState(true),[reports,setReports]=useState(false);return <><PageHead eyebrow="Cuenta y preferencias" title="Configuración" description="Administra los datos y notificaciones de la empresa."/><div className="settings-layout"><aside className="panel settings-nav"><button className="active"><Building2Icon/> Empresa</button><button><UserRound/> Usuarios y permisos</button><button><BellIcon/> Notificaciones</button><button><ShieldCheck/> Seguridad</button></aside><section className="panel settings-form"><h2>Datos de la empresa</h2><p>Información visible para la municipalidad y gestores autorizados.</p><div className="form-row"><label>Razón social<input defaultValue="Mercado Central SpA"/></label><label>RUT<input defaultValue="76.432.198-5" readOnly/></label></div><label>Actividad económica<input defaultValue="Venta y distribución de alimentos"/></label><div className="form-row"><label>Correo<input type="email" defaultValue="administracion@mercadocentral.cl"/></label><label>Teléfono<input defaultValue="+56 2 2456 7890"/></label></div><label>Dirección<input defaultValue="Av. Irarrázaval 2450, Ñuñoa"/></label><hr/><h3>Notificaciones</h3><Toggle label="Avisos por correo" value={email} set={setEmail}/><Toggle label="Cambios en solicitudes de retiro" value={pickup} set={setPickup}/><Toggle label="Resumen ambiental mensual" value={reports} set={setReports}/><div className="form-actions"><button className="primary" onClick={()=>notify("Configuración guardada")}>Guardar cambios</button></div></section></div></>}

function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <div className="toggle-row"><span>{label}</span><button className={value?"on":""} onClick={()=>set(!value)}><i/></button></div>}
function Empty({text}:{text:string}){return <div className="empty"><AlertCircle/><strong>{text}</strong><span>Prueba cambiando la búsqueda o el filtro.</span></div>}
function Building2Icon(){return <Settings/>} function BellIcon(){return <AlertCircle/>}
