"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, Building2, CheckCircle2, Clock3, Download, Eye, FileCheck2, Filter, MapPin, Recycle, Search, ShieldCheck, Truck, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { getMunicipalWorkspace, MunicipalOperation, updateMunicipalPickup } from "@/lib/supabase/data";
import { getAccessRole } from "@/lib/access";

const labels:Record<string,string>={requested:"Pendiente",confirmed:"Confirmado",on_route:"En ruta",collected:"Retirado",delivered:"Entregado",completed:"Completado",rejected:"Rechazado",cancelled:"Cancelado"};
const formatDate=(date:string)=>new Intl.DateTimeFormat("es-CL",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${date}T12:00:00`));
const material=(op:MunicipalOperation)=>op.pickup_items.map(item=>item.waste_declarations?.waste_types?.name).filter(Boolean).join(" · ")||"Sin material informado";
const total=(op:MunicipalOperation)=>op.pickup_items.map(item=>`${Number(item.estimated_quantity).toLocaleString("es-CL")} ${item.unit==="unit"?"un.":item.unit}`).join(" + ")||"—";

export default function MunicipalPage(){
  const router=useRouter();
  const [operations,setOperations]=useState<MunicipalOperation[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [selected,setSelected]=useState<MunicipalOperation|null>(null),[updating,setUpdating]=useState(false);
  useEffect(()=>{getAccessRole().then(role=>{if(role!=="municipal") router.replace("/login?portal=municipal")})},[router]);
  const load=async()=>{setLoading(true);setError("");try{const data=await getMunicipalWorkspace();if(!data?.membership) setError("No tienes un perfil municipal activo. Solicita a la administración municipal que asigne tu rol.");else setOperations(data.operations)}catch{setError("No fue posible cargar las operaciones. Verifica la conexión y tus permisos.")}finally{setLoading(false)}};
  useEffect(()=>{load()},[]);
  const rows=useMemo(()=>operations.filter(op=>`${op.code} ${op.organizations?.legal_name??""} ${op.organizations?.rut??""} ${material(op)}`.toLowerCase().includes(query.toLowerCase())),[operations,query]);
  const pending=operations.filter(op=>op.status==="requested").length;
  const confirmed=operations.filter(op=>op.status==="confirmed"||op.status==="on_route").length;
  const weight=operations.reduce((sum,op)=>sum+op.pickup_items.reduce((s,item)=>s+(item.unit==="kg"?Number(item.estimated_quantity):0),0),0);
  const flash=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(""),3500)};
  async function changeStatus(status:"confirmed"|"rejected"){if(!selected)return;setUpdating(true);try{await updateMunicipalPickup({pickupId:selected.id,status});setSelected(null);await load();flash(status==="confirmed"?"Retiro confirmado y registrado en la bitácora.":"Solicitud rechazada y registrada en la bitácora.")}catch(e){flash(e instanceof Error?e.message:"No se pudo actualizar la operación.")}finally{setUpdating(false)}}
  return <main className="municipal-page"><header className="muni-header"><div className="muni-brand"><span><Building2/></span><div><strong>Portal Municipal</strong><small>CircularMuni · Gestión Ambiental</small></div></div><nav><button className="active"><BarChart3/> Monitoreo</button><button><Truck/> Operaciones</button><button><Building2/> Empresas</button><button><FileCheck2/> Reportes</button></nav><Link href="/login"><ArrowLeft/> Cambiar acceso</Link></header><div className="muni-content">
    <section className="module-head"><div><p className="eyebrow"><span/> ACCESO FUNCIONARIO</p><h1>Centro de control comunal</h1><p>Supervisa solicitudes, trazabilidad y cumplimiento con información registrada por las empresas.</p></div><button className="primary" onClick={()=>flash("La exportación estará disponible con los registros filtrados.")}><Download/> Exportar reporte</button></section>
    {error?<section className="panel municipal-empty"><ShieldCheck/><h2>Acceso municipal requerido</h2><p>{error}</p><Link className="primary" href="/login?portal=municipal">Ingresar como funcionario</Link></section>:<>
    <section className="stats"><article><div className="stat-icon green"><Building2/></div><div><span>Empresas con operación</span><strong>{new Set(operations.map(x=>x.requester_organization_id)).size}</strong><p>Con solicitudes registradas</p></div></article><article><div className="stat-icon amber"><Clock3/></div><div><span>Por revisar</span><strong>{pending}</strong><p>{confirmed} retiros confirmados</p></div></article><article><div className="stat-icon blue"><Recycle/></div><div><span>Material programado</span><strong>{weight.toLocaleString("es-CL")} <small>kg</small></strong><p>Solo cantidades declaradas en kg</p></div></article><article><div className="stat-icon purple"><ShieldCheck/></div><div><span>Operaciones activas</span><strong>{operations.filter(x=>!["completed","cancelled","rejected"].includes(x.status)).length}</strong><p>Trazabilidad en curso</p></div></article></section>
    <div className="muni-grid"><section className="panel muni-map"><div className="panel-head"><div><h2>Actividad territorial</h2><p>Solicitudes por comuna declarada</p></div><span className="live-dot">DATOS ACTUALIZADOS</span></div><div className="map-surface map-3d">{operations.slice(0,4).map((op,index)=><i key={op.id} className={`pin p${index+1} ${op.priority==="urgent"?"alert":""}`} title={op.organizations?.legal_name}><Truck/></i>)}<div className="map-legend"><span><i/> Solicitud registrada</span><span><i/> Prioridad alta</span></div></div></section><section className="panel muni-alerts"><div className="panel-head"><div><h2>Bandeja de revisión</h2><p>Acciones pendientes</p></div><b>{pending}</b></div>{pending?operations.filter(x=>x.status==="requested").slice(0,3).map(op=><button key={op.id} onClick={()=>setSelected(op)}><span className={op.priority==="urgent"?"danger":"warning"}>{op.priority==="urgent"?<AlertTriangle/>:<Clock3/>}</span><div><strong>{op.organizations?.trade_name||op.organizations?.legal_name}</strong><small>{op.code} · {formatDate(op.preferred_date)}</small></div><Eye/></button>):<div className="muni-no-alerts"><CheckCircle2/> No hay solicitudes pendientes.</div>}</section></div>
    <section className="panel module-panel muni-operations"><div className="panel-head"><div><h2>Operaciones registradas</h2><p>Consulta y resuelve solicitudes reales de retiro.</p></div></div><div className="toolbar"><div className="search wide"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar empresa, RUT, código o material"/></div><button className="date-filter"><Filter/> Todos los estados</button></div><div className="table-wrap"><table><thead><tr><th>EMPRESA</th><th>MATERIAL</th><th>CANTIDAD</th><th>FECHA</th><th>ESTADO</th><th>ACCIÓN</th></tr></thead><tbody>{rows.map(op=><tr key={op.id}><td><div className="company-dot"><Building2/></div><div><strong>{op.organizations?.trade_name||op.organizations?.legal_name||"Empresa"}</strong><small>{op.organizations?.rut||"RUT no informado"}</small></div></td><td>{material(op)}</td><td><strong>{total(op)}</strong></td><td>{formatDate(op.preferred_date)}</td><td><span className={`request-status ${op.status}`}>{labels[op.status]||op.status}</span></td><td><button className="row-action" onClick={()=>setSelected(op)}><Eye/> Revisar</button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="municipal-empty small"><Recycle/><h2>No hay operaciones para mostrar</h2><p>Las solicitudes creadas por empresas autorizadas aparecerán aquí.</p></div>}{loading&&<div className="municipal-empty small"><Clock3/><h2>Cargando operaciones</h2><p>Consultando los registros autorizados…</p></div>}</div></section></>}
    <footer><span>Información protegida · Cada cambio queda registrado</span><span><Users/> Acceso restringido a personal autorizado</span></footer></div>
    {selected&&<div className="modal-backdrop" onMouseDown={()=>!updating&&setSelected(null)}><section className="modal municipal-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X/></button><div className="modal-icon truck"><Truck/></div><h2>{selected.code}</h2><p>{selected.organizations?.legal_name} · {material(selected)}</p><div className="operation-detail"><span><Building2/> {selected.organizations?.rut}</span><span><MapPin/> {selected.sites?.address_line||"Dirección no informada"}</span><span><Clock3/> {formatDate(selected.preferred_date)} · {selected.time_window_start.slice(0,5)}–{selected.time_window_end.slice(0,5)}</span><span><Users/> {selected.contact_name} · {selected.contact_phone}</span></div>{selected.status==="requested"?<div className="form-actions"><button className="secondary" disabled={updating} onClick={()=>changeStatus("rejected")}>Rechazar</button><button className="primary" disabled={updating} onClick={()=>changeStatus("confirmed")}><CheckCircle2/> {updating?"Guardando…":"Confirmar retiro"}</button></div>:<div className="notice"><CheckCircle2/> Esta operación está en estado: {labels[selected.status]||selected.status}.</div>}</section></div>}
    {notice&&<div className="toast"><CheckCircle2/>{notice}</div>}
  </main>
}
