"use client";
import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Building2, CheckCircle2, Eye, EyeOff, Leaf, LockKeyhole, Mail, Recycle, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { demoCredentials, startDemoSession } from "@/lib/access";

export default function LoginPage(){
  const router=useRouter(), params=useSearchParams(), municipal=params.get("portal")==="municipal";
  const [register,setRegister]=useState(false),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const d=new FormData(e.currentTarget),email=String(d.get("email")).trim().toLowerCase(),password=String(d.get("password"));const demoRole=email===demoCredentials.company.email&&password===demoCredentials.company.password?"company":email===demoCredentials.municipal.email&&password===demoCredentials.municipal.password?"municipal":null;const s=createClient();if(!s&&!register){if(!demoRole){setMessage("Correo o contraseña incorrectos.");setLoading(false);return;}startDemoSession(demoRole);router.replace(demoRole==="municipal"?"/municipal":"/empresa");return;}if(!s){setMessage("Configura las variables de Supabase para registrar una empresa.");setLoading(false);return;}
    if(register){const {data,error}=await s.auth.signUp({email,password,options:{data:{account_type:"company",full_name:d.get("fullName"),legal_name:d.get("legalName"),trade_name:d.get("tradeName"),rut:d.get("rut"),phone:d.get("phone"),address:d.get("address"),commune:d.get("commune"),region:"Región Metropolitana"}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Cuenta creada. Revisa tu correo para confirmar el acceso.");else router.replace("/empresa");}
    else {const {data,error}=await s.auth.signInWithPassword({email,password});if(error)setMessage("Correo o contraseña incorrectos.");else {const {data:role}=await s.from("memberships").select("role").eq("user_id",data.user.id).eq("is_active",true).in("role",["municipal_admin","municipal_inspector"]).maybeSingle();if(municipal&&!role)setMessage("Esta cuenta no tiene un rol municipal activo.");else router.replace(role?"/municipal":"/empresa");}}setLoading(false);
  }
  return <main className="auth-page"><section className="auth-story"><Link href="/"><ArrowLeft/> Volver al portal</Link><div className="auth-brand"><span><Recycle/></span> CircularMuni</div><div className="story-copy"><span>GESTIÓN AMBIENTAL MUNICIPAL</span><h1>Residuo trazable.<br/>Decisión responsable.</h1><p>Una plataforma para empresas y municipios que requieren control operacional, evidencia y seguimiento ambiental.</p><div><b><CheckCircle2/> Trazabilidad completa</b><b><CheckCircle2/> Gestores autorizados</b><b><CheckCircle2/> Certificación digital</b></div></div><small><Leaf/> Plataforma de economía circular</small></section><section className="auth-form-wrap"><div className="auth-form"><div className="auth-mobile-brand"><Recycle/> CircularMuni</div><span className="auth-symbol"><Building2/></span><h2>{register?"Registra tu empresa":municipal?"Acceso funcionario":"Bienvenido de vuelta"}</h2><p>{register?"Crea la cuenta responsable de la gestión ambiental.":municipal?"Ingresa con una cuenta institucional y rol municipal asignado.":"Ingresa al portal de gestión de residuos."}</p><form onSubmit={submit}>{register&&<><div className="form-row"><label>Nombre completo<input name="fullName" required/></label><label>Teléfono<input name="phone" required/></label></div><label>Razón social<input name="legalName" required/></label><div className="form-row"><label>Nombre de fantasía<input name="tradeName"/></label><label>RUT empresa<input name="rut" required/></label></div><label>Dirección del establecimiento<input name="address" required/></label><label>Comuna<input name="commune" defaultValue="Ñuñoa" required/></label></>}<label>Correo electrónico<div className="input-icon"><Mail/><input name="email" type="email" required placeholder={municipal?"nombre@municipalidad.cl":"administracion@empresa.cl"}/></div></label><label>Contraseña<div className="input-icon"><LockKeyhole/><input name="password" type={show?"text":"password"} minLength={8} required placeholder="Mínimo 8 caracteres"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{message&&<div className="auth-message">{message}</div>}<button className="auth-submit" disabled={loading}>{loading?"Procesando…":register?"Crear cuenta empresa":"Ingresar"}</button></form>{!municipal&&<div className="auth-switch">{register?"¿Ya tienes una cuenta?":"¿Tu empresa aún no está registrada?"}<button onClick={()=>{setRegister(!register);setMessage("")}}>{register?"Iniciar sesión":"Registrar empresa"}</button></div>}<small>Al continuar aceptas los Términos de uso y la Política de privacidad.</small></div></section></main>
}
