"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Building2, CheckCircle2, Eye, EyeOff, Leaf, LockKeyhole, Mail, Recycle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import Link from "next/link";

export default function LoginPage(){
  const [register,setRegister]=useState(false),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState(""); const router=useRouter();
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");const s=createClient();if(!s){setMessage("Configura las variables de Supabase.");setLoading(false);return}const d=new FormData(e.currentTarget);const email=String(d.get("email")),password=String(d.get("password"));
    if(register){const {data,error}=await s.auth.signUp({email,password,options:{data:{account_type:"company",full_name:d.get("fullName"),legal_name:d.get("legalName"),trade_name:d.get("tradeName"),rut:d.get("rut"),phone:d.get("phone"),address:d.get("address"),commune:d.get("commune"),region:"Región Metropolitana"}}});if(error)setMessage(error.message);else if(!data.session)setMessage("Cuenta creada. Revisa tu correo para confirmar el acceso.");else router.push("/");}
    else{const {error}=await s.auth.signInWithPassword({email,password});if(error)setMessage("Correo o contraseña incorrectos.");else router.push("/");}setLoading(false)}
  return <main className="auth-page"><section className="auth-story"><Link href="/"><ArrowLeft/> Volver a la demostración</Link><div className="auth-brand"><span><Recycle/></span> CircularMuni</div><div className="story-copy"><span>GESTIÓN AMBIENTAL MUNICIPAL</span><h1>Cada residuo cuenta.<br/>Cada acción transforma.</h1><p>Conectamos empresas, gestores y municipalidades para construir una comuna más limpia y circular.</p><div><b><CheckCircle2/> Trazabilidad completa</b><b><CheckCircle2/> Gestores autorizados</b><b><CheckCircle2/> Certificación digital</b></div></div><small><Leaf/> Plataforma oficial de economía circular</small></section><section className="auth-form-wrap"><div className="auth-form"><div className="auth-mobile-brand"><Recycle/> CircularMuni</div><span className="auth-symbol"><Building2/></span><h2>{register?"Registra tu empresa":"Bienvenido de vuelta"}</h2><p>{register?"Crea la cuenta responsable de la gestión ambiental.":"Ingresa al portal de gestión de residuos."}</p><form onSubmit={submit}>{register&&<><div className="form-row"><label>Nombre completo<input name="fullName" required placeholder="Carolina Muñoz"/></label><label>Teléfono<input name="phone" required placeholder="+56 9 1234 5678"/></label></div><label>Razón social<input name="legalName" required placeholder="Mercado Central SpA"/></label><div className="form-row"><label>Nombre de fantasía<input name="tradeName" placeholder="Mercado Central"/></label><label>RUT empresa<input name="rut" required placeholder="76.432.198-5"/></label></div><label>Dirección del establecimiento<input name="address" required placeholder="Av. Irarrázaval 2450"/></label><label>Comuna<select name="commune"><option>Ñuñoa</option><option>Providencia</option><option>Santiago</option><option>Macul</option><option>La Reina</option></select></label></>}<label>Correo electrónico<div className="input-icon"><Mail/><input name="email" type="email" required placeholder="administracion@empresa.cl"/></div></label><label>Contraseña<div className="input-icon"><LockKeyhole/><input name="password" type={show?"text":"password"} minLength={8} required placeholder="Mínimo 8 caracteres"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{message&&<div className="auth-message">{message}</div>}<button className="auth-submit" disabled={loading}>{loading?"Procesando...":register?"Crear cuenta empresa":"Ingresar al portal"}</button></form><div className="auth-switch">{register?"¿Ya tienes una cuenta?":"¿Tu empresa aún no está registrada?"}<button onClick={()=>{setRegister(!register);setMessage("")}}>{register?"Iniciar sesión":"Registrar empresa"}</button></div><small>Al continuar aceptas los Términos de uso y la Política de privacidad.</small></div></section></main>
}
